### PR TITLE
Bug fixes and clean up code

### PR DESCRIPTION
**Pull request by spcasey**

### CODE REVIEW

**Review by foodhype — CHANGES_REQUESTED** [review]
Make sure the target directory is in your .gitignore file and remove all files in the target directory from this change.

**Comment by spcasey** [comment]
> Make sure the target directory is in your .gitignore file and remove all files in the target directory from this change.

Whoops thank you - fixed

**Comment by foodhype** [comment]
You still have 130+ files changed. You need to remove the target directory from your commit. See `git rm` command.

**Comment by spcasey** [comment]
> You still have 130+ files changed. You need to remove the target directory from your commit. See `git rm` command.

Ope forgot to close - will re-push

**Pull request closed without merging**
